name: Build and Deploy React App

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Build React App
        run: |
          npm install
          npm run build

      - name: Build Docker Image
        run: docker build -t rutvikmalaviya0322/react-app .

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image
        run: docker push rutvikmalaviya0322/react-app

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull rutvikmalaviya0322/react-app
            docker stop react-container || true
            docker rm react-container || true
            docker run -d -p 3000:80 --name react-container rutvikmalaviya0322/react-app